# in _config.yml
title: Python para Ingenieros
author: Pedro Jorge De Los Santos
logo: img/logo.png
copyright: "2026"
execute:
  execute_notebooks: "off"
latex:
  latex_documents:
     targetname: book.tex
     
html:
    extra_footer: |
        <div>
            <!-- Default Statcounter code for Python para ingenieros
            https://jorgedelossantos.github.io/apuntes-python/ -->
            <script type="text/javascript">
            var sc_project=13087844; 
            var sc_invisible=1; 
            var sc_security="a797accf"; 
            </script>
            <script type="text/javascript"
            src="https://www.statcounter.com/counter/counter.js"
            async></script>
            <noscript><div class="statcounter"><a title="Web Analytics"
            href="https://statcounter.com/" target="_blank"><img
            class="statcounter"
            src="https://c.statcounter.com/13087844/0/a797accf/1/"
            alt="Web Analytics"
            referrerPolicy="no-referrer-when-downgrade"></a></div></noscript>
            <!-- End of Statcounter Code -->
        </div>

